// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {email} from '../models';
import {proxy} from '../models';
import {task} from '../models';

export function AddOutlookAccounts(arg1:string):Promise<Record<string, any>>;

export function AddProxyManual(arg1:string):Promise<Record<string, any>>;

export function BatchDeleteResults(arg1:Array<string>):Promise<Record<string, any>>;

export function BatchTestProxies():Promise<Record<string, any>>;

export function CancelUpdate():Promise<Record<string, any>>;

export function CheckLicense():Promise<Record<string, any>>;

export function CheckServerHealth():Promise<Record<string, any>>;

export function CheckUpdate():Promise<Record<string, any>>;

export function ClearKiroResults():Promise<Record<string, any>>;

export function ClearOutlookAccounts():Promise<Record<string, any>>;

export function ClearProxyPool():Promise<Record<string, any>>;

export function DeleteOutlookAccount(arg1:string):Promise<Record<string, any>>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function ExportKiroResults(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function ExportProxyYAML():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<string>>;

export function GetMoeMailConfigs():Promise<Array<email.MoeMailConfig>>;

export function GetMoeMailDomains(arg1:string):Promise<Record<string, any>>;

export function GetOutlookAccounts():Promise<Array<Record<string, any>>>;

export function GetOverview():Promise<Record<string, any>>;

export function GetProxyPolicy():Promise<proxy.ProxyPolicy>;

export function GetProxyPool():Promise<Record<string, any>>;

export function GetResults(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTaskStatus():Promise<Record<string, any>>;

export function ImportKiroResults():Promise<Record<string, any>>;

export function ImportOutlookFile(arg1:string):Promise<Record<string, any>>;

export function ImportProxyYAML():Promise<Record<string, any>>;

export function ImportProxyYAMLFromURL(arg1:string):Promise<Record<string, any>>;

export function LogoutLicense():Promise<Record<string, any>>;

export function ParseOutlook(arg1:string):Promise<Record<string, any>>;

export function RemoveProxy(arg1:string):Promise<Record<string, any>>;

export function ResetAllProxyStatus():Promise<Record<string, any>>;

export function ResetDataDir():Promise<Record<string, any>>;

export function ResetProxyStatus(arg1:string):Promise<Record<string, any>>;

export function RunHealthCheck(arg1:number):Promise<Record<string, any>>;

export function SaveMoeMailConfigs(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectOutlookFile():Promise<string>;

export function SetDataDir(arg1:string):Promise<Record<string, any>>;

export function SetLocalCanvasFingerprint(arg1:number,arg2:Array<number>):Promise<Record<string, any>>;

export function StartTask(arg1:task.StartTaskRequest):Promise<Record<string, any>>;

export function StopTask():Promise<Record<string, any>>;

export function TestMoeMailConnection(arg1:string):Promise<Record<string, any>>;

export function TestPoolProxy(arg1:string):Promise<Record<string, any>>;

export function TestProxy(arg1:string):Promise<Record<string, any>>;

export function UpdateAccountStatus(arg1:string,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function UpdateProxyPolicy(arg1:proxy.ProxyPolicy):Promise<Record<string, any>>;

export function ValidateLicense(arg1:string):Promise<Record<string, any>>;

export function VerifyLicense(arg1:string):Promise<Record<string, any>>;
