// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOutlookAccounts(arg1) {
  return window['go']['main']['App']['AddOutlookAccounts'](arg1);
}

export function AddProxyManual(arg1) {
  return window['go']['main']['App']['AddProxyManual'](arg1);
}

export function BatchDeleteResults(arg1) {
  return window['go']['main']['App']['BatchDeleteResults'](arg1);
}

export function BatchTestProxies() {
  return window['go']['main']['App']['BatchTestProxies']();
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function CheckServerHealth() {
  return window['go']['main']['App']['CheckServerHealth']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearKiroResults() {
  return window['go']['main']['App']['ClearKiroResults']();
}

export function ClearOutlookAccounts() {
  return window['go']['main']['App']['ClearOutlookAccounts']();
}

export function ClearProxyPool() {
  return window['go']['main']['App']['ClearProxyPool']();
}

export function DeleteOutlookAccount(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccount'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExportKiroResults(arg1, arg2) {
  return window['go']['main']['App']['ExportKiroResults'](arg1, arg2);
}

export function ExportProxyYAML() {
  return window['go']['main']['App']['ExportProxyYAML']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMoeMailConfigs() {
  return window['go']['main']['App']['GetMoeMailConfigs']();
}

export function GetMoeMailDomains(arg1) {
  return window['go']['main']['App']['GetMoeMailDomains'](arg1);
}

export function GetOutlookAccounts() {
  return window['go']['main']['App']['GetOutlookAccounts']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetProxyPolicy() {
  return window['go']['main']['App']['GetProxyPolicy']();
}

export function GetProxyPool() {
  return window['go']['main']['App']['GetProxyPool']();
}

export function GetResults(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetResults'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function ImportKiroResults() {
  return window['go']['main']['App']['ImportKiroResults']();
}

export function ImportOutlookFile(arg1) {
  return window['go']['main']['App']['ImportOutlookFile'](arg1);
}

export function ImportProxyYAML() {
  return window['go']['main']['App']['ImportProxyYAML']();
}

export function ImportProxyYAMLFromURL(arg1) {
  return window['go']['main']['App']['ImportProxyYAMLFromURL'](arg1);
}

export function LogoutLicense() {
  return window['go']['main']['App']['LogoutLicense']();
}

export function ParseOutlook(arg1) {
  return window['go']['main']['App']['ParseOutlook'](arg1);
}

export function RemoveProxy(arg1) {
  return window['go']['main']['App']['RemoveProxy'](arg1);
}

export function ResetAllProxyStatus() {
  return window['go']['main']['App']['ResetAllProxyStatus']();
}

export function ResetDataDir() {
  return window['go']['main']['App']['ResetDataDir']();
}

export function ResetProxyStatus(arg1) {
  return window['go']['main']['App']['ResetProxyStatus'](arg1);
}

export function RunHealthCheck(arg1) {
  return window['go']['main']['App']['RunHealthCheck'](arg1);
}

export function SaveMoeMailConfigs(arg1) {
  return window['go']['main']['App']['SaveMoeMailConfigs'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectOutlookFile() {
  return window['go']['main']['App']['SelectOutlookFile']();
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetLocalCanvasFingerprint(arg1, arg2) {
  return window['go']['main']['App']['SetLocalCanvasFingerprint'](arg1, arg2);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function TestMoeMailConnection(arg1) {
  return window['go']['main']['App']['TestMoeMailConnection'](arg1);
}

export function TestPoolProxy(arg1) {
  return window['go']['main']['App']['TestPoolProxy'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function UpdateAccountStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccountStatus'](arg1, arg2, arg3);
}

export function UpdateProxyPolicy(arg1) {
  return window['go']['main']['App']['UpdateProxyPolicy'](arg1);
}

export function ValidateLicense(arg1) {
  return window['go']['main']['App']['ValidateLicense'](arg1);
}

export function VerifyLicense(arg1) {
  return window['go']['main']['App']['VerifyLicense'](arg1);
}
